server:
  port: 8888
  servlet:
    session:
      timeout: -1

spring:
  application:
    name: app
  profiles:
    active: dev, prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/airline_db?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Europe/Moscow
    username: root
    password: root
    hikari:
      leak-detection-threshold: 60000
      maximum-pool-size: 20
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
        jdbc:
          time_zone: Europe/Moscow

#logging:

